---
## Default configuration values
#    Necessary for config library, not used in R file
#    No need to change these values
default:
  dbms: null
  user: null
  password: null
  server: null
  port: null
  oracleDriver: null
  pathToDriver: null
  cdm_schema: null
  vocabulary_schema: null
  cohort_schema: null

## Connection details
#    Replace with your connection details
#    Used as input to DatabaseConnector::createConnectionDetails()
#    see the function documentation for more information
#    Please check carefully which details are required for your dbms
#    as not all of these details may be required.
#    cdm_schema should point to the OMOP CDM schema
#    vocabulary_schema should point to the schema where the vocabulary tables are stored
config:
  dbms: ''
  user: ''
  password: ''
  server: ''
  port: 5432
  oracleDriver: null
  pathToDriver: ''
  cdm_schema: ''
  vocabulary_schema: ''
  cohort_schema: ''